### ISSUE TITLE
Radio as button group doesn't trigger CDD

### ISSUE THREAD

**Issue by trob** [Fabrik/fabrik#1224]
http://www.fabrikar.com/forums/index.php?threads/where-for-dbjoin-using-data-in-current-form.38195/
ok, if radio element is set to buttongroup=no

**Comment by cheesegrits** [comment]
Hmmm.  the only solution I can think of for that is to add an element model method, like changeEvent(), which in the main element model just return 'change', but can be overridden in specific element plugins to return 'click' if that's what the element knows it needs.  Then in the calc element's elementJavascript(), where it builds the $opts->observe array (a list of element full names used by the calc), loop through the that array, load up the element model by name, call $elementModel->changeEvent() for each one, build an $opts->observeEvents array, and in the calc's attachToForm() method in the JS, use that for attaching the event that triggers the calc.

Long way round the houses, but I don't see any other way round it.

**Comment by trob** [comment]
It's not only calc but also CDD

**Comment by cheesegrits** [comment]
Ignore all that.  I can just add a getChangeEvent() in element.js, and override it in specific elements, like yesno.js, then call that in the calc's init.

**Comment by cheesegrits** [comment]
OK, should be fixed as of https://github.com/Fabrik/fabrik/commit/f6483849f4b4d30c764dd800478960491f9090ad

**Comment by Duke3D** [comment]
Has the fix been confirmed?  Does something need to be added to the element setup for calc to be triggered by a button group?  Adding elements in watchlist with ..._raw did not help.

**Comment by trob** [comment]
The fix was for yesno only, radiobutton is still missing.
https://github.com/Fabrik/fabrik/pull/1531

I don't know if it can be removed from yesno then (extends radio)

**Comment by cheesegrits** [comment]
Should be fixed in https://github.com/Fabrik/fabrik/commit/5267bd42bf5276bbe558ae1166b510e7b2010808
